name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to latest version
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py  # Fixed path - your files are in root, not model/

      - name: Evaluate Model
        run: |
          python evaluate.py  # Fixed path

      - name: Run Unit Tests
        run: |
          python test_model.py  # Fixed - your test file is test_model.py, not in tests/

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: customer-segmentation-model
          path: model/customer_segmentation.pkl

      - name: Upload Clustered Data
        uses: actions/upload-artifact@v4
        with:
          name: clustered-customer-data
          path: data/clustered_customers.csv
